import type { ScenarioManifest } from '../types'

function escapeTableCell(value: string): string {
  return value.replace(/\|/g, '\\|').replace(/\n/g, ' ')
}

function renderListItems(items: readonly string[]): string {
  if (items.length === 0) return '_（无）_\n'
  return items.map((item) => `- ${item}`).join('\n') + '\n'
}

/** Render human-readable SCENARIOS.md from manifest. */
export function renderManifestMarkdown(manifest: ScenarioManifest): string {
  const lines: string[] = [
    '# NovaExcel 行为场景清单',
    '',
    '> @generated by @novasheet/mbd — 改 scenarios/*.md 后执行 `bun run sync:mbd-manifest`',
    '',
    '| id | layer | status | summary |',
    '| --- | --- | --- | --- |',
  ]

  for (const scenario of manifest.scenarios) {
    lines.push(
      `| ${scenario.id} | ${scenario.layer} | ${scenario.status ?? ''} | ${escapeTableCell(scenario.summary)} |`,
    )
  }

  lines.push('')

  for (const scenario of manifest.scenarios) {
    lines.push(`## ${scenario.id}`, '')
    lines.push(`- **layer**: ${scenario.layer}`)
    lines.push(`- **summary**: ${scenario.summary}`)
    if (scenario.status !== undefined) {
      lines.push(`- **status**: ${scenario.status}`)
    }
    lines.push('')

    if (scenario.userStory !== undefined) {
      lines.push('### User Story', '', scenario.userStory, '')
    }

    lines.push('### Given', '', renderListItems(scenario.given))
    lines.push('### When', '', renderListItems(scenario.when))
    lines.push('### Then', '', renderListItems(scenario.then))
  }

  return lines.join('\n').trimEnd() + '\n'
}
