export interface ToolbarColorSwatch {
  readonly color: string
  readonly label: string
}

export const fillPaletteRows: readonly (readonly ToolbarColorSwatch[])[] = [
  [
    { color: '#000000', label: '黑色' },
    { color: '#434343', label: '深灰 4' },
    { color: '#666666', label: '深灰 3' },
    { color: '#999999', label: '深灰 2' },
    { color: '#b7b7b7', label: '深灰 1' },
    { color: '#cccccc', label: '浅灰 1' },
    { color: '#d9d9d9', label: '浅灰 2' },
    { color: '#efefef', label: '浅灰 3' },
    { color: '#f3f3f3', label: '浅灰 4' },
    { color: '#ffffff', label: '白色' },
  ],
  [
    { color: '#cc0000', label: '红色 1' },
    { color: '#e69138', label: '橙色 1' },
    { color: '#f1c232', label: '黄色 1' },
    { color: '#ffff00', label: '亮黄色' },
    { color: '#00ff00', label: '亮绿色' },
    { color: '#00ffff', label: '青色' },
    { color: '#4a86e8', label: '蓝色 1' },
    { color: '#0000ff', label: '亮蓝色' },
    { color: '#9900ff', label: '紫色 1' },
    { color: '#ff00ff', label: '洋红' },
  ],
  [
    { color: '#f4cccc', label: '红色 2' },
    { color: '#fce5cd', label: '橙色 2' },
    { color: '#fff2cc', label: '黄色 2' },
    { color: '#d9ead3', label: '绿色 2' },
    { color: '#d0e0e3', label: '青色 2' },
    { color: '#cfe2f3', label: '蓝色 2' },
    { color: '#d9d2e9', label: '紫色 2' },
    { color: '#ead1dc', label: '粉色 2' },
  ],
  [
    { color: '#ea9999', label: '红色 3' },
    { color: '#f9cb9c', label: '橙色 3' },
    { color: '#ffe599', label: '黄色 3' },
    { color: '#b6d7a8', label: '绿色 3' },
    { color: '#a2c4c9', label: '青色 3' },
    { color: '#9fc5e8', label: '蓝色 3' },
    { color: '#b4a7d6', label: '紫色 3' },
    { color: '#d5a6bd', label: '粉色 3' },
  ],
  [
    { color: '#e06666', label: '红色 4' },
    { color: '#f6b26b', label: '橙色 4' },
    { color: '#ffd966', label: '黄色 4' },
    { color: '#93c47d', label: '绿色 4' },
    { color: '#76a5af', label: '青色 4' },
    { color: '#6fa8dc', label: '蓝色 4' },
    { color: '#8e7cc3', label: '紫色 4' },
    { color: '#c27ba0', label: '粉色 4' },
  ],
  [
    { color: '#cc4125', label: '红色 5' },
    { color: '#e69138', label: '橙色 5' },
    { color: '#f1c232', label: '黄色 5' },
    { color: '#6aa84f', label: '绿色 5' },
    { color: '#45818e', label: '青色 5' },
    { color: '#3d85c6', label: '蓝色 5' },
    { color: '#674ea7', label: '紫色 5' },
    { color: '#a64d79', label: '粉色 5' },
  ],
  [
    { color: '#a61c00', label: '红色 6' },
    { color: '#b45f06', label: '橙色 6' },
    { color: '#bf9000', label: '黄色 6' },
    { color: '#38761d', label: '绿色 6' },
    { color: '#134f5c', label: '青色 6' },
    { color: '#0b5394', label: '蓝色 6' },
    { color: '#351c75', label: '紫色 6' },
    { color: '#741b47', label: '粉色 6' },
  ],
  [
    { color: '#85200c', label: '红色 7' },
    { color: '#783f04', label: '橙色 7' },
    { color: '#7f6000', label: '黄色 7' },
    { color: '#274e13', label: '绿色 7' },
    { color: '#0c343d', label: '青色 7' },
    { color: '#073763', label: '蓝色 7' },
    { color: '#20124d', label: '紫色 7' },
    { color: '#4c1130', label: '粉色 7' },
  ],
]

export const standardFillColors: readonly ToolbarColorSwatch[] = [
  { color: '#000000', label: '黑色' },
  { color: '#ffffff', label: '白色' },
  { color: '#4285f4', label: '蓝色' },
  { color: '#ea4335', label: '红色' },
  { color: '#fbbc04', label: '黄色' },
  { color: '#34a853', label: '绿色' },
  { color: '#ff6d01', label: '橙色' },
  { color: '#46bdc6', label: '青色' },
]
