import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

import { readManifest } from '@zhiguang/novasheet-mbd'
import {
  collectScenarioIdsFromTestRoots,
  computeScenarioCoverage,
} from '../../../packages/react/scripts/check-scenario-coverage.ts'

const COVERED_FILL = '#34a353'
const MISSING_FILL = '#ea4335'

const scriptDir = dirname(fileURLToPath(import.meta.url))
const storybookRoot = resolve(scriptDir, '..')
const repoRoot = resolve(storybookRoot, '../..')

const manifestPath = join(repoRoot, 'packages/react/tests/excel/scenarios.manifest.json')
const testRoot = join(repoRoot, 'packages/react/tests/excel')
const outPath = join(storybookRoot, 'src/generated/excel-scenario-board.ts')

export interface ExcelScenarioBoardRow {
  readonly layer: string
  readonly id: string
  readonly summary: string
  readonly userStory: string
  readonly manifestStatus: 'draft' | 'implemented'
  readonly coverage: 'covered' | 'missing'
  readonly fillColor: typeof COVERED_FILL | typeof MISSING_FILL
}

async function buildRows(): Promise<{
  readonly rows: readonly ExcelScenarioBoardRow[]
  readonly stats: { readonly covered: number; readonly total: number }
  readonly generatedAt: string
}> {
  const manifest = await readManifest(manifestPath)
  const foundIds = collectScenarioIdsFromTestRoots([testRoot])
  const report = computeScenarioCoverage(manifest, foundIds)
  const coveredSet = new Set(report.covered)

  const rows: ExcelScenarioBoardRow[] = manifest.scenarios.map((scenario) => {
    const coverage = coveredSet.has(scenario.id) ? 'covered' : 'missing'
    return {
      layer: scenario.layer,
      id: scenario.id,
      summary: scenario.summary,
      userStory: scenario.userStory,
      manifestStatus: scenario.status,
      coverage,
      fillColor: coverage === 'covered' ? COVERED_FILL : MISSING_FILL,
    }
  })

  return {
    rows,
    stats: { covered: report.covered.length, total: report.expectedIds.length },
    generatedAt: new Date().toISOString(),
  }
}

function emitSource(payload: Awaited<ReturnType<typeof buildRows>>): string {
  const body = JSON.stringify(payload.rows, null, 2)
  return `/** @generated by sync-excel-scenario-board — do not edit */
export interface ExcelScenarioBoardRow {
  readonly layer: string
  readonly id: string
  readonly summary: string
  readonly userStory: string
  readonly manifestStatus: 'draft' | 'implemented'
  readonly coverage: 'covered' | 'missing'
  readonly fillColor: '#34a353' | '#ea4335'
}

export const EXCEL_SCENARIO_BOARD_GENERATED_AT = ${JSON.stringify(payload.generatedAt)}

export const EXCEL_SCENARIO_BOARD_STATS = ${JSON.stringify(payload.stats)} as const

export const EXCEL_SCENARIO_BOARD_ROWS: readonly ExcelScenarioBoardRow[] = ${body}
`
}

async function main(): Promise<void> {
  const payload = await buildRows()
  mkdirSync(dirname(outPath), { recursive: true })
  writeFileSync(outPath, emitSource(payload), 'utf8')
  console.log(
    `excel scenario board: ${payload.stats.covered}/${payload.stats.total} covered → ${outPath}`,
  )
}

if ((import.meta as { main?: boolean }).main) {
  await main()
}
